### **Description**:Learn how to use tensors in Tensorflow

#### Prop
- nd-array
- GPU support
- Computational Graph / Backpropagation
- Immutable

In [2]:
import tensorflow as tf

x = tf.constant(4)
print(x)

tf.Tensor(4, shape=(), dtype=int32)


In [3]:
x = tf.constant(4, shape=(1, 1), dtype=tf.float32)
print(x)

tf.Tensor([[4.]], shape=(1, 1), dtype=float32)


In [4]:
x = tf.constant([[1, 2, 3], [4, 5, 6]])
print(x)

tf.Tensor(
[[1 2 3]
 [4 5 6]], shape=(2, 3), dtype=int32)


In [7]:
x = tf.ones((3, 3), dtype=tf.int32)
x

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]], dtype=int32)>

In [8]:
x = tf.eye(3)
print(x)

tf.Tensor(
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]], shape=(3, 3), dtype=float32)


In [9]:
x = tf.random.normal((3, 3), mean=0, stddev=1)
x

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[ 0.42517745,  1.1771523 ,  0.4431411 ],
       [-0.5400549 , -0.9585258 ,  2.1323535 ],
       [-1.4758095 , -1.0421426 , -1.0948182 ]], dtype=float32)>

In [10]:
x = tf.random.uniform((3, 3), minval=0, maxval=1)
x

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[0.6809813 , 0.9085413 , 0.49832952],
       [0.653072  , 0.32443833, 0.6748222 ],
       [0.7071954 , 0.77471435, 0.2026279 ]], dtype=float32)>

In [12]:
x = tf.range(10)
x

# cast
x = tf.cast(x, dtype=tf.float32)
x

<tf.Tensor: shape=(10,), dtype=float32, numpy=array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.], dtype=float32)>

In [14]:
# elementwise
x = tf.constant([1, 2, 3])
y = tf.constant([4, 5, 6])

z = tf.add(x, y) # or x + y
print(z.numpy())

[5 7 9]


In [16]:
z = tf.subtract(x, y)
z

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([-3, -3, -3], dtype=int32)>

In [17]:
# dot product
z = tf.tensordot(x, y, axes=1)
print(z)

tf.Tensor(32, shape=(), dtype=int32)


In [21]:
x = tf.random.normal((2, 3))
y = tf.random.normal((3, 2))

In [23]:
z = tf.matmul(x, y)
print(z)

tf.Tensor(
[[-0.1179302  -2.0876818 ]
 [-1.7435453   0.04571003]], shape=(2, 2), dtype=float32)


In [25]:
# slicing and indexing
x = tf.constant([[1, 2, 3, 4], [5, 6, 7, 8]])
x[0] # first row

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([1, 2, 3, 4], dtype=int32)>

In [26]:
x[1] # second row

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([5, 6, 7, 8], dtype=int32)>

In [28]:
x[:, 0:1] # all row but col 1

<tf.Tensor: shape=(2, 1), dtype=int32, numpy=
array([[1],
       [5]], dtype=int32)>

In [33]:
x[:,...]

<tf.Tensor: shape=(2, 4), dtype=int32, numpy=
array([[1, 2, 3, 4],
       [5, 6, 7, 8]], dtype=int32)>

In [34]:
x = tf.random.normal((2, 3))
x

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[ 0.9053482 , -0.15713677, -0.25948063],
       [ 0.30730852,  0.654095  ,  0.17707115]], dtype=float32)>

In [38]:
x = tf.reshape(x, (3, 2))
x

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[ 0.9053482 , -0.15713677],
       [-0.25948063,  0.30730852],
       [ 0.654095  ,  0.17707115]], dtype=float32)>

In [39]:
x = x.numpy()
print(type(x))
x

<class 'numpy.ndarray'>


array([[ 0.9053482 , -0.15713677],
       [-0.25948063,  0.30730852],
       [ 0.654095  ,  0.17707115]], dtype=float32)

In [41]:
x = tf.convert_to_tensor(x)
x

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[ 0.9053482 , -0.15713677],
       [-0.25948063,  0.30730852],
       [ 0.654095  ,  0.17707115]], dtype=float32)>

In [42]:
x = tf.constant(['Patrick', 'Max', 'Prateek'])
x

<tf.Tensor: shape=(3,), dtype=string, numpy=array([b'Patrick', b'Max', b'Prateek'], dtype=object)>

In [43]:
x = tf.Variable([1, 2, 3])
x

<tf.Variable 'Variable:0' shape=(3,) dtype=int32, numpy=array([1, 2, 3], dtype=int32)>